### ISSUE TITLE
LAcheck LAS-file error: "Trace point sum != aligned interval"

### ISSUE THREAD

**Issue by DDDolle** [thegenemyers/DALIGNER#58] opened 2017-03-15 11:21 UTC
Hi,

I have encountered an error that I can't explain in a few of my 'daligner' runs.

My DB has 128 blocks of 200Mb that I want to overlap as preparation for error-correction using FALCON.

All 8256 overlap runs together produce 16384 intermediate LAS files (prior to merging) of which 4 show the error mentioned in the header.

Surprisingly tho this error doesn't seem to be symmetric: the LAS file "[DB].X.[DB].Y" is OK while the file "[DB].Y.[DB].X" produced at the same time by the same 'daligner' run is not. Two of the four files show this behavior. The last two however are from the same run and both defect. In all cases X=128 (i.e. the last block in the DB).

My 'daligner' command is: 

  "daligner -M12 -mdust -mtan -mrep1 -mrep4 -mrep16 -b -e0.70 [DB].Y [DB].X"

and I am using commit "a9458dcb34eca61513c994f4217fb7f75915e25c"

Best,

 Dirk

**Comment by pb-cdunn** [comment] 2017-09-15 07:16
A user sent me data for a seg-fault, and I think I have reproduced the problem.

    $ LA4Falcon -H500 -of ../raw_reads.db ../raw_reads.104.las > out.la4.txt
    LA4Falcon: Index 64618683 out of bounds 4699235 (Load_Read)

    $ LAcheck -v ../raw_reads.db ../raw_reads.104.las
    raw_reads.104: Trace point sum != aligned interval

@thegenemyers, I have the DB (17GB) and the .las (3GB). I will save these in Menlo Park for you, in case the cause of error is not obvious. I will try find out the DALIGNER run which led to this, and the commit-SHA1 that was used. Of course, the DALIGNER used is probably not quite up-to-date with your latest code, so I will try to get some time to sync up.

@DDDolle, I cannot find that commit-SHA1 (a9458...) in this repository. Typo?

**Comment by thegenemyers** [comment] 2017-09-15 08:00
Christopher,

    This problem has occurred several times and my recollection is that 
it has not been fully
resolved for lack of a reproducible test case for me to work with.

    It would be extremely helpful to me if you could pass me the dB and 
the *exact call to
daligner* that lead to the problem.  I'm am 99% certain the problem 
occurred during the
daligner run that produced the .las, so I need to know exactly how 
daligner was being run
(and exactly which version if not the latest).

    I look forward to seeing you in Menlo park -- with the data sets it 
should be straightforward
for me to then track down the bug.

    -- Gene

**Comment by DDDolle** [comment] 2017-09-15 08:14
@pb-cdunn 

Hmm, isn't it this one: https://github.com/thegenemyers/DALIGNER/commit/a9458dcb34eca61513c994f4217fb7f75915e25c

**Comment by pb-cdunn** [comment] 2017-09-15 15:19
@DDDolle, ah, you're right. But that is an old commit, from November 2016.. I think this was fixed in December.

@thegenemyers, yes, if we cannot resolve this by syncing to the latest DALIGNER, then I will make the test-case available to you on-site in Menlo Park. But I think you can safely ignore this for now.

**Comment by pb-cdunn** [comment] 2017-10-03 17:34
Update on my previous comment: The problem reported by the user was likely a result of an I/O error, as `LAcheck` failed on the `.las` file. #67 should prevent those in the future. So I don't know of any current problem.

**Closed** 2018-01-03 13:56 UTC
